pov_infile : /store_new/mch/msopr/osm/MISC/GIT_DATA/python/pollen_calibration/ART_POV_iconR19B08-grid_0001.gb2
pov_outfile : /scratch/mch/mlbadaou/rtcal_SYLVA/realtime_pollen_calibration/test_local/test_tune_rbf_mq_switch
t2m_file : /store_new/mch/msopr/osm/MISC/GIT_DATA/python/pollen_calibration/T_2M_KENDA-CH1_2024020112.gb2
const_file : /store_new/mch/msopr/osm/MISC/GIT_DATA/python/pollen_calibration/CLON_CLAT_ICON-CH1.gb2
station_obs_file : /store_new/mch/msopr/osm/MISC/GIT_DATA/python/pollen_calibration/pollen_measured_2024020118.atab
station_mod_file : /store_new/mch/msopr/osm/MISC/GIT_DATA/python/pollen_calibration/pollen_modelled_2024020118.atab
hour_incr : 1
weighting_type: switch
max_miss_stns : 4
max_param:
  ALNU: 3.389
  BETU: 4.046
  POAC: 1.875
  CORY: 7.738
min_param:
  ALNU: 0.235
  BETU: 0.222
  POAC: 0.405
  CORY: 0.216
ipstyle: rbf_mq
eps_val: 1

